package ai.mailmind.service;

import ai.mailmind.api.ApiModels.*; import ai.mailmind.domain.*; import org.springframework.context.annotation.Profile; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.security.oauth2.client.OAuth2AuthorizedClientService; import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.nio.charset.StandardCharsets; import java.time.Instant; import java.util.*; import java.util.regex.*;

/** Reads Gmail through the access token issued by Google OAuth. Refresh tokens are handled by Spring's authorized-client manager in a production persistent store. */
@Service @Profile("google") public class GmailSyncService {
 private final OAuth2AuthorizedClientService clients; private final MailService mail;
 public GmailSyncService(OAuth2AuthorizedClientService c,MailService m){clients=c;mail=m;}
 @SuppressWarnings("unchecked") public int sync(Authentication auth,User user){
  if(!(auth instanceof OAuth2AuthenticationToken oauth)) throw new IllegalStateException("Sign in with Google first");
  var client=clients.loadAuthorizedClient("google",auth.getName()); if(client==null) throw new IllegalStateException("Google authorization was not found. Sign in again.");
  var http=RestClient.builder().baseUrl("https://gmail.googleapis.com/gmail/v1/users/me").defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+client.getAccessToken().getTokenValue()).build();
  int count=0;String token=null;do{String pageToken=token;Map<String,Object> list=http.get().uri(builder->{var request=builder.path("/messages").queryParam("labelIds","INBOX").queryParam("maxResults",100).queryParam("q","newer_than:7d");if(pageToken!=null)request.queryParam("pageToken",pageToken);return request.build();}).retrieve().body(Map.class);
  for(Object raw:Optional.ofNullable((List<Object>)list.get("messages")).orElse(List.of())){Map<String,Object> ref=(Map<String,Object>)raw;Map<String,Object> msg=http.get().uri("/messages/{id}?format=full",ref.get("id")).retrieve().body(Map.class);Map<String,Object> payload=(Map<String,Object>)msg.get("payload");Map<String,String> headers=headers((List<Object>)payload.get("headers"));String body=body(payload);if(body.isBlank())body=(String)msg.getOrDefault("snippet","");mail.ingest(user,new ImportEmail((String)msg.get("id"),(String)msg.get("threadId"),headers.getOrDefault("From","Unknown sender"),headers.get("To"),headers.get("Subject"),body,html(payload,http,(String)msg.get("id")),Instant.ofEpochMilli(Long.parseLong((String)msg.get("internalDate")))));count++;}token=list==null?null:(String)list.get("nextPageToken");}while(token!=null&&!token.isBlank());
 return count;
 }
 @SuppressWarnings("unchecked") public GmailWriteResult createReplyDraft(Authentication auth,Email email,GmailComposeRequest request){return write(auth,email,request,false);}
 @SuppressWarnings("unchecked") public GmailWriteResult sendReply(Authentication auth,Email email,GmailComposeRequest request){return write(auth,email,request,true);}
 @SuppressWarnings("unchecked") private GmailWriteResult write(Authentication auth,Email email,GmailComposeRequest request,boolean send){
  var http=http(auth);String subject=email.subject==null?"":email.subject.replaceAll("[\\r\\n]"," ");if(!subject.regionMatches(true,0,"Re:",0,3))subject="Re: "+subject;String recipient=address(email.sender);String mime=mime(recipient,subject,request.body(),Optional.ofNullable(request.attachments()).orElse(List.of()));String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(mime.getBytes(StandardCharsets.UTF_8));Map<String,Object> message=new HashMap<>();message.put("raw",raw);if(email.threadId!=null&&!email.threadId.isBlank())message.put("threadId",email.threadId);Map<String,Object> payload=send?message:Map.of("message",message);String path=send?"/messages/send":"/drafts";System.out.println("[Gmail] "+(send?"Sending":"Creating draft for")+" thread="+email.threadId);Map<String,Object> response=http.post().uri(path).contentType(MediaType.APPLICATION_JSON).body(payload).retrieve().body(Map.class);if(response==null)throw new IllegalStateException("Gmail returned an empty response.");Object messagePart=send?response:response.get("message");Map<String,Object> result=messagePart instanceof Map<?,?> m?(Map<String,Object>)m:response;System.out.println("[Gmail] "+(send?"Message sent successfully.":"Draft created successfully."));return new GmailWriteResult(String.valueOf(response.get("id")),String.valueOf(result.getOrDefault("threadId",email.threadId)));
  }
 @SuppressWarnings("unchecked") public List<IncomingAttachment> attachments(Authentication auth,Email email){Map<String,Object> message=http(auth).get().uri("/messages/{id}?format=full",email.providerId).retrieve().body(Map.class);return collectAttachments((Map<String,Object>)message.get("payload"));}
 @SuppressWarnings("unchecked") public DownloadedFile attachment(Authentication auth,Email email,String attachmentId){System.out.println("[Gmail] Downloading attachment for message="+email.providerId);Map<String,Object> message=http(auth).get().uri("/messages/{id}?format=full",email.providerId).retrieve().body(Map.class);IncomingAttachment meta=collectAttachments((Map<String,Object>)message.get("payload")).stream().filter(file->file.id().equals(attachmentId)).findFirst().orElse(new IncomingAttachment(attachmentId,"attachment","application/octet-stream",0));Map<String,Object> response=http(auth).get().uri("/messages/{message}/attachments/{attachment}",email.providerId,attachmentId).retrieve().body(Map.class);Object data=response==null?null:response.get("data");if(!(data instanceof String encoded))throw new IllegalStateException("Gmail returned an empty attachment.");System.out.println("[Gmail] Downloaded attachment: "+meta.name());return new DownloadedFile(Base64.getUrlDecoder().decode(encoded),meta.name(),meta.contentType());}
 @SuppressWarnings("unchecked") private List<IncomingAttachment> collectAttachments(Map<String,Object> part){if(part==null)return List.of();List<IncomingAttachment> out=new ArrayList<>();String name=(String)part.get("filename");String type=(String)part.getOrDefault("mimeType","application/octet-stream");Map<String,Object> body=part.get("body") instanceof Map<?,?> map?(Map<String,Object>)map:Map.of();Object attachmentId=body.get("attachmentId");if(name!=null&&!name.isBlank()&&attachmentId instanceof String id){Object size=body.getOrDefault("size",0);out.add(new IncomingAttachment(id,name,type,size instanceof Number n?n.longValue():0));}for(Object child:Optional.ofNullable((List<Object>)part.get("parts")).orElse(List.of()))out.addAll(collectAttachments((Map<String,Object>)child));return out;}
 public record DownloadedFile(byte[] bytes,String name,String contentType) {}
 private String mime(String recipient,String subject,String html,List<GmailAttachment> attachments){String boundary="mailmind-"+UUID.randomUUID();StringBuilder out=new StringBuilder("To: ").append(recipient).append("\r\nSubject: ").append(subject).append("\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=\"").append(boundary).append("\"\r\n\r\n");out.append("--").append(boundary).append("\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n").append(encoded(html.getBytes(StandardCharsets.UTF_8))).append("\r\n");for(GmailAttachment file:attachments){byte[] bytes;try{bytes=Base64.getDecoder().decode(file.data());}catch(IllegalArgumentException ex){throw new IllegalArgumentException("One attachment could not be decoded.");}if(bytes.length>10*1024*1024)throw new IllegalArgumentException("Each attachment must be 10 MB or smaller.");String name=file.name().replaceAll("[\\r\\n\\\"]","_");String type=(file.contentType()==null||file.contentType().isBlank()?"application/octet-stream":file.contentType().replaceAll("[\\r\\n]",""));out.append("--").append(boundary).append("\r\nContent-Type: ").append(type).append("; name=\"").append(name).append("\"\r\nContent-Disposition: attachment; filename=\"").append(name).append("\"\r\nContent-Transfer-Encoding: base64\r\n\r\n").append(encoded(bytes)).append("\r\n");}return out.append("--").append(boundary).append("--\r\n").toString();}
 private String encoded(byte[] value){return Base64.getMimeEncoder(76,"\r\n".getBytes(StandardCharsets.US_ASCII)).encodeToString(value);}
 private RestClient http(Authentication auth){if(!(auth instanceof OAuth2AuthenticationToken))throw new IllegalStateException("Sign in with Google first.");var client=clients.loadAuthorizedClient("google",auth.getName());if(client==null)throw new IllegalStateException("Google authorization was not found. Sign out and sign in again to grant Gmail compose access.");return RestClient.builder().baseUrl("https://gmail.googleapis.com/gmail/v1/users/me").defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+client.getAccessToken().getTokenValue()).build();}
 private String address(String source){Matcher m=Pattern.compile("[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}",Pattern.CASE_INSENSITIVE).matcher(source==null?"":source);if(!m.find())throw new IllegalArgumentException("The sender does not have a valid reply address.");return m.group();}
 @SuppressWarnings("unchecked") private Map<String,String> headers(List<Object> values){Map<String,String> out=new HashMap<>();for(Object v:Optional.ofNullable(values).orElse(List.of())){Map<String,Object> h=(Map<String,Object>)v;out.put((String)h.get("name"),(String)h.get("value"));}return out;}
  @SuppressWarnings("unchecked") private String body(Map<String,Object> p){if(p==null)return "";Object data=p.get("body") instanceof Map<?,?> m?m.get("data"):null;if(data instanceof String s)return tidy(clean(preserveLinks(new String(Base64.getUrlDecoder().decode(s),StandardCharsets.UTF_8))));for(Object child:Optional.ofNullable((List<Object>)p.get("parts")).orElse(List.of())){String found=body((Map<String,Object>)child);if(!found.isBlank())return found;}return "";}
  private String html(Map<String,Object> p,RestClient http,String messageId){return htmlParts(p,http,messageId).stream().max(Comparator.comparingInt(this::htmlQuality)).orElse(null);}
  @SuppressWarnings("unchecked") private List<String> htmlParts(Map<String,Object> p,RestClient http,String messageId){if(p==null)return List.of();List<String> out=new ArrayList<>();if("text/html".equalsIgnoreCase((String)p.get("mimeType"))){Map<String,Object> body=p.get("body") instanceof Map<?,?> map?(Map<String,Object>)map:Map.of();Object data=body.get("data");if(data instanceof String value)out.add(new String(Base64.getUrlDecoder().decode(value),StandardCharsets.UTF_8));else if(body.get("attachmentId") instanceof String attachmentId){Map<String,Object> response=http.get().uri("/messages/{message}/attachments/{attachment}",messageId,attachmentId).retrieve().body(Map.class);if(response!=null&&response.get("data") instanceof String value)out.add(new String(Base64.getUrlDecoder().decode(value),StandardCharsets.UTF_8));}}for(Object child:Optional.ofNullable((List<Object>)p.get("parts")).orElse(List.of()))out.addAll(htmlParts((Map<String,Object>)child,http,messageId));return out;}
  private int htmlQuality(String value){String lower=value.toLowerCase(Locale.ROOT);int richness=(lower.contains("<table")?20000:0)+(lower.contains("<img")?15000:0)+(lower.contains("<style")?10000:0)+(lower.contains("background")?3000:0);return richness+Math.min(value.length(),12000);}
  private String preserveLinks(String value){return value.replaceAll("(?is)<a\\b[^>]*?href\\s*=\\s*[\"']([^\"']+)[\"'][^>]*>(.*?)</a>","[$2]($1)");}
  private String tidy(String value){String out=value.replaceAll("(?i)&#(?:x[0-9a-f]+|[0-9]+);"," ").replace("\uFEFF"," ").replace("â€™","'").replace("â€˜","'").replace("â€“","-").replace("â€”","-").replaceAll("[ \\t]{2,}"," ").replaceAll("\\n{3,}","\n\n").trim();for(String marker:List.of("\nAt Unstop", "\nIf you'd prefer not to receive", "\nPrivacy Policy", "\nTerms and Conditions")){int index=out.toLowerCase(Locale.ROOT).indexOf(marker.toLowerCase(Locale.ROOT));if(index>350){out=out.substring(0,index).trim();break;}}return out.length()>5000?out.substring(0,4997)+"...":out;}
  private String clean(String value){return value.replaceAll("(?is)<(script|style).*?>.*?</\\1>"," ").replaceAll("(?i)<br\\s*/?>|</p>|</div>|</li>","\n").replaceAll("(?s)<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replace("&lt;","<").replace("&gt;",">").replaceAll("[ \\t]+"," ").replaceAll("\\s*>\\s*","\n> ").replaceAll("(?m)(On .+? wrote:)\\s*","$1\n").replaceAll("\\n{3,}","\n\n").trim();}
}
