package ai.mailmind.service;

import ai.mailmind.domain.Email; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.util.*;

@Service public class OpenRouterReplyService {
 private final String baseUrl,key,model; private final AnalysisService fallback; private final ObjectMapper json;
 public OpenRouterReplyService(@Value("${app.ai.base-url}") String baseUrl,@Value("${app.ai.api-key:}") String key,@Value("${app.ai.model:openrouter/free}") String model,AnalysisService fallback,ObjectMapper json){this.baseUrl=baseUrl;this.key=key;this.model=model;this.fallback=fallback;this.json=json;}
 @SuppressWarnings("unchecked") public String draft(Email email,String intent,String tone,String signatureName){
  if(key.isBlank()){System.out.println("[OpenRouter] Reply blocked: OPENROUTER_API_KEY is not configured.");throw new IllegalStateException("OpenRouter is not configured. Set OPENROUTER_API_KEY and restart the backend.");}
  String context=(email.body==null?"":email.body).replaceAll("\\s+"," ");if(context.length()>8000)context=context.substring(0,8000);
  String prompt="Draft only the email reply (no subject line, no markdown). Tone: "+tone+". Sender: "+email.sender+". Subject: "+email.subject+". Incoming email: "+context+". User's intended response: "+intent+". Finish with a suitable closing (for example, Best regards) followed by this exact signature name on the final line: "+signatureName;
  try {System.out.println("[OpenRouter] Sending reply request. model="+model+", baseUrl="+baseUrl);Map<String,Object> payload=Map.of("model",model,"messages",List.of(Map.of("role","system","content","You are a concise, helpful email assistant."),Map.of("role","user","content",prompt)));Map<String,Object> response=RestClient.builder().baseUrl(baseUrl).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+key).defaultHeader(HttpHeaders.CONTENT_TYPE,MediaType.APPLICATION_JSON_VALUE).build().post().uri("/chat/completions").body(payload).retrieve().body(Map.class);var choices=(List<Object>)response.get("choices");if(choices!=null&&!choices.isEmpty()){var choice=(Map<String,Object>)choices.getFirst();var message=(Map<String,Object>)choice.get("message");var content=(String)message.get("content");if(content!=null&&!content.isBlank()){System.out.println("[OpenRouter] Reply generated successfully.");return content.trim();}}throw new IllegalStateException("OpenRouter returned no reply choices.");}catch(Exception error){System.out.println("[OpenRouter] Reply request failed: "+error.getClass().getSimpleName()+": "+error.getMessage());throw new IllegalStateException("OpenRouter reply generation failed. Check the backend console for [OpenRouter] logs.");}
 }
 @SuppressWarnings("unchecked") public String summarize(Email email){
  if(key.isBlank())throw new IllegalStateException("OpenRouter is not configured. Set OPENROUTER_API_KEY and restart the backend.");
  String body=(email.body==null?"":email.body).replaceAll("\\s+"," ");if(body.length()>8000)body=body.substring(0,8000);
  try{System.out.println("[OpenRouter] Sending summary request. model="+model);Map<String,Object> payload=Map.of("model",model,"messages",List.of(Map.of("role","system","content","Summarize emails concisely in 2-4 sentences, including actions or deadlines."),Map.of("role","user","content","Subject: "+email.subject+"\nFrom: "+email.sender+"\nEmail: "+body)));Map<String,Object> response=RestClient.builder().baseUrl(baseUrl).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+key).defaultHeader(HttpHeaders.CONTENT_TYPE,MediaType.APPLICATION_JSON_VALUE).build().post().uri("/chat/completions").body(payload).retrieve().body(Map.class);var choices=(List<Object>)response.get("choices");if(choices!=null&&!choices.isEmpty()){var message=(Map<String,Object>)((Map<String,Object>)choices.getFirst()).get("message");var content=(String)message.get("content");if(content!=null&&!content.isBlank()){System.out.println("[OpenRouter] Summary generated successfully.");return content.trim();}}throw new IllegalStateException("OpenRouter returned no summary choices.");}catch(Exception error){System.out.println("[OpenRouter] Summary request failed: "+error.getClass().getSimpleName()+": "+error.getMessage());throw new IllegalStateException("OpenRouter summary generation failed. Check the backend console for [OpenRouter] logs.");}
 }
 @SuppressWarnings("unchecked") public List<String> extractTasks(List<Email> emails){
  if(key.isBlank())throw new IllegalStateException("OpenRouter is not configured. Set OPENROUTER_API_KEY and restart the backend.");
  StringBuilder context=new StringBuilder();for(Email email:emails.stream().limit(25).toList()){String body=(email.body==null?"":email.body).replaceAll("\\s+"," ");if(body.length()>1200)body=body.substring(0,1200);context.append("\n---\nFrom: ").append(email.sender).append("\nSubject: ").append(email.subject).append("\nBody: ").append(body);}
  try{System.out.println("[OpenRouter] Sending active-task extraction request. model="+model);Map<String,Object> payload=Map.of("model",model,"messages",List.of(Map.of("role","system","content","You identify only real, actionable work from emails. Ignore newsletters, promotions, automated notices, thank-yous, and vague FYIs. Return strict JSON only."),Map.of("role","user","content","Extract at most 15 concise active tasks from these inbox emails. Combine duplicates. Every item must begin with an action verb. Return exactly a JSON array of strings, with no markdown or explanation. Emails:"+context)));Map<String,Object> response=RestClient.builder().baseUrl(baseUrl).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+key).defaultHeader(HttpHeaders.CONTENT_TYPE,MediaType.APPLICATION_JSON_VALUE).build().post().uri("/chat/completions").body(payload).retrieve().body(Map.class);var choices=(List<Object>)response.get("choices");if(choices==null||choices.isEmpty())throw new IllegalStateException("OpenRouter returned no task choices.");var message=(Map<String,Object>)((Map<String,Object>)choices.getFirst()).get("message");String content=(String)message.get("content");if(content==null||content.isBlank())throw new IllegalStateException("OpenRouter returned an empty task response.");String clean=content.trim().replaceAll("(?s)^```(?:json)?\\s*|\\s*```$","");List<String> result=json.readValue(clean,new TypeReference<List<String>>(){}).stream().filter(Objects::nonNull).map(v->v.replaceAll("<[^>]*>"," ").replaceAll("\\s+"," ").trim()).filter(v->!v.isBlank()).distinct().limit(15).toList();System.out.println("[OpenRouter] Active tasks generated: "+result.size());return result;}catch(Exception error){System.out.println("[OpenRouter] Task extraction failed: "+error.getClass().getSimpleName()+": "+error.getMessage());throw new IllegalStateException("OpenRouter task generation failed. Check the backend console for [OpenRouter] logs.");}
 }
 @SuppressWarnings("unchecked") public List<ExtractedTask> extractTasksWithSources(List<Email> emails){
  if(key.isBlank())throw new IllegalStateException("OpenRouter is not configured. Set OPENROUTER_API_KEY and restart the backend.");
  StringBuilder context=new StringBuilder();for(Email email:emails.stream().limit(25).toList()){String body=(email.body==null?"":email.body).replaceAll("\\s+"," ");if(body.length()>1200)body=body.substring(0,1200);context.append("\n---\nSOURCE_ID: ").append(email.providerId).append("\nFrom: ").append(email.sender).append("\nSubject: ").append(email.subject).append("\nBody: ").append(body);}
  try{System.out.println("[OpenRouter] Sending source-linked task extraction request. model="+model);Map<String,Object> payload=Map.of("model",model,"messages",List.of(Map.of("role","system","content","You identify only real, actionable work from emails. Ignore newsletters, promotions, automated notices, thank-yous, and vague FYIs. Return strict JSON only."),Map.of("role","user","content","Extract at most 15 concise active tasks. Each task must remain linked to one exact SOURCE_ID below. Return exactly a JSON array of objects in this form: [{\"sourceId\":\"exact source id\",\"title\":\"Action verb task\"}]. No markdown or explanation. Emails:"+context)));Map<String,Object> response=RestClient.builder().baseUrl(baseUrl).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+key).defaultHeader(HttpHeaders.CONTENT_TYPE,MediaType.APPLICATION_JSON_VALUE).build().post().uri("/chat/completions").body(payload).retrieve().body(Map.class);var choices=(List<Object>)response.get("choices");if(choices==null||choices.isEmpty())throw new IllegalStateException("OpenRouter returned no task choices.");var message=(Map<String,Object>)((Map<String,Object>)choices.getFirst()).get("message");String content=(String)message.get("content");if(content==null||content.isBlank())throw new IllegalStateException("OpenRouter returned an empty task response.");String clean=content.trim().replaceAll("(?s)^```(?:json)?\\s*|\\s*```$","");List<Map<String,Object>> raw=json.readValue(clean,new TypeReference<List<Map<String,Object>>>(){});List<ExtractedTask> result=raw.stream().filter(Objects::nonNull).map(item->new ExtractedTask(String.valueOf(item.getOrDefault("sourceId","")),String.valueOf(item.getOrDefault("title","")))).map(item->new ExtractedTask(item.sourceId(),item.title().replaceAll("<[^>]*>"," ").replaceAll("\\s+"," ").trim())).filter(item->!item.sourceId().isBlank()&&!item.title().isBlank()).distinct().limit(15).toList();System.out.println("[OpenRouter] Source-linked active tasks generated: "+result.size());return result;}catch(Exception error){System.out.println("[OpenRouter] Task extraction failed: "+error.getClass().getSimpleName()+": "+error.getMessage());throw new IllegalStateException("OpenRouter task generation failed. Check the backend console for [OpenRouter] logs.");}
 }
 public record ExtractedTask(String sourceId,String title) {}
}
